# Generated by Django 5.2.1 on 2025-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='clean_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Tozalangan javob matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='clean_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Tozalangan savol matni'),
        ),
    ]
