# Generated by Django 5.2.1 on 2025-05-31 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_answer_clean_text_question_clean_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Foydalanuvchi extension’dan necha marta foydalanganini ko‘rsatadi.', verbose_name='Foydalanish soni')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Foydalanuvchi oxirgi marta extension’dan foydalangan vaqt, har safar yangilanadi.', verbose_name='Oxirgi foydalanish')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Foydalanish yozuvi yaratilgan vaqt, avtomatik to‘ldiriladi.', verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(help_text='Ushbu faoliyat qaysi foydalanuvchiga tegishli ekanligini ko‘rsatadi.', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi faoliyati',
                'verbose_name_plural': 'Foydalanuvchi faoliyatlari',
            },
        ),
    ]
